contact_links:
  - name: WHATWG Living HTML Specification
    about: "If you are reporting a problem relative to HTML diagnostics you will need to provide a referece to the WHATWG Living HTML specification that points out the discrepancy".
    url: https://html.spec.whatwg.org/multipage/
